/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package VistaAdministrador;

/**
 *
 * @author SARA
 */
public class Administrador_RegistrarUsers extends javax.swing.JFrame {

    /** Creates new form InterfazAdministrador */
    public Administrador_RegistrarUsers() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new RSMaterialComponent.RSPanelMaterial();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new RSMaterialComponent.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNombres = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico = new javax.swing.JLabel();
        jtxtApellidos = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico1 = new javax.swing.JLabel();
        jtxtCorreo = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico2 = new javax.swing.JLabel();
        jlbCorreoElectronico3 = new javax.swing.JLabel();
        jcbxTipoEmpleado = new RSMaterialComponent.RSComboBoxMaterial();
        jlbCorreoElectronico4 = new javax.swing.JLabel();
        jcbxTipoDoc = new RSMaterialComponent.RSComboBoxMaterial();
        jlbCorreoElectronico5 = new javax.swing.JLabel();
        jtxtNumDocumento = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico6 = new javax.swing.JLabel();
        jlbCorreoElectronico7 = new javax.swing.JLabel();
        jtxtTelefono = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxtContraseña = new RSMaterialComponent.RSPasswordIconTwo();
        jlbCorreoElectronico8 = new javax.swing.JLabel();
        jtxtToken = new RSMaterialComponent.RSTextFieldIconTwo();
        btnSeleccionarImagen = new RSMaterialComponent.RSButtonMaterialOne();
        btnAgregar = new RSMaterialComponent.RSButtonIconShadow();
        btnBorrar = new RSMaterialComponent.RSButtonIconShadow();
        btnEditar = new RSMaterialComponent.RSButtonIconShadow();
        jlbCorreoElectronico9 = new javax.swing.JLabel();
        jlbCorreoElectronico10 = new javax.swing.JLabel();
        jlbCorreoElectronico11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setBgShade(new java.awt.Color(255, 255, 255));
        Panel.setIntensity(5);
        Panel.setPixels(0);
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Correo", "Rol", "Tipo doc.", "Nº doc.", "Telf.", "Token", "Imagen"
            }
        ));
        tblEmpleados.setBackgoundHead(new java.awt.Color(51, 51, 51));
        tblEmpleados.setBackgoundHover(new java.awt.Color(102, 102, 102));
        tblEmpleados.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        tblEmpleados.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        tblEmpleados.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblEmpleados);

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1010, 350));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Registro de Empleados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jtxtNombres.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNombres.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtNombres.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtNombres.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtNombres.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        jtxtNombres.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtNombres.setPlaceholder("Nombres");
        jtxtNombres.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 30));

        jlbCorreoElectronico.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico.setText("Nombres");
        jPanel1.add(jlbCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtApellidos.setForeground(new java.awt.Color(102, 102, 102));
        jtxtApellidos.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtApellidos.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtApellidos.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtApellidos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        jtxtApellidos.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtApellidos.setPlaceholder("Apellidos");
        jtxtApellidos.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 200, 30));

        jlbCorreoElectronico1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico1.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico1.setText("Apellidos");
        jPanel1.add(jlbCorreoElectronico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jtxtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtCorreo.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtCorreo.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtCorreo.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtCorreo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EMAIL);
        jtxtCorreo.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtCorreo.setPlaceholder(" abc@mail.com");
        jtxtCorreo.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 200, 30));

        jlbCorreoElectronico2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico2.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico2.setText("Contraseña");
        jPanel1.add(jlbCorreoElectronico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        jlbCorreoElectronico3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico3.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico3.setText("Tipo de Empleado");
        jPanel1.add(jlbCorreoElectronico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jcbxTipoEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        jcbxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleado", "Administrador", " " }));
        jcbxTipoEmpleado.setColorMaterial(new java.awt.Color(255, 153, 0));
        jPanel1.add(jcbxTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 30));

        jlbCorreoElectronico4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico4.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico4.setText("Token");
        jPanel1.add(jlbCorreoElectronico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jcbxTipoDoc.setForeground(new java.awt.Color(51, 51, 51));
        jcbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "Pasaporte", "Carné de Extranjería" }));
        jcbxTipoDoc.setColorMaterial(new java.awt.Color(255, 153, 0));
        jPanel1.add(jcbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 200, 30));

        jlbCorreoElectronico5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico5.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico5.setText("Tipo de Doc. Identidad");
        jPanel1.add(jlbCorreoElectronico5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jtxtNumDocumento.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNumDocumento.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtNumDocumento.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtNumDocumento.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtNumDocumento.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT);
        jtxtNumDocumento.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtNumDocumento.setPlaceholder("55555555");
        jtxtNumDocumento.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtNumDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 200, 30));

        jlbCorreoElectronico6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico6.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico6.setText("Agregar");
        jPanel1.add(jlbCorreoElectronico6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, -1, -1));

        jlbCorreoElectronico7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico7.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico7.setText("Telf. de Contacto");
        jPanel1.add(jlbCorreoElectronico7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jtxtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        jtxtTelefono.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtTelefono.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtTelefono.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtTelefono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE);
        jtxtTelefono.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtTelefono.setPlaceholder("999999999");
        jtxtTelefono.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 200, 30));

        jtxtContraseña.setForeground(new java.awt.Color(102, 102, 102));
        jtxtContraseña.setToolTipText("");
        jtxtContraseña.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtContraseña.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtContraseña.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtContraseña.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtContraseña.setPlaceholder("* * * * * * * ");
        jtxtContraseña.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 200, 30));

        jlbCorreoElectronico8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico8.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico8.setText("Correo electrónico");
        jPanel1.add(jlbCorreoElectronico8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jtxtToken.setForeground(new java.awt.Color(102, 102, 102));
        jtxtToken.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtToken.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtToken.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtToken.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        jtxtToken.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtToken.setPlaceholder("Ingrese su token");
        jtxtToken.setSelectionColor(new java.awt.Color(255, 153, 0));
        jtxtToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTokenActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, 30));

        btnSeleccionarImagen.setBackground(new java.awt.Color(102, 102, 102));
        btnSeleccionarImagen.setText("Seleccionar Imagen");
        btnSeleccionarImagen.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnSeleccionarImagen.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnSeleccionarImagen.setRound(30);
        btnSeleccionarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarImagenMouseClicked(evt);
            }
        });
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 140, 30));

        btnAgregar.setBackground(new java.awt.Color(0, 204, 102));
        btnAgregar.setBackgroundHover(new java.awt.Color(0, 102, 0));
        btnAgregar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnAgregar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, -1, -1));

        btnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        btnBorrar.setBackgroundHover(new java.awt.Color(153, 0, 0));
        btnBorrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnBorrar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 204, 0));
        btnEditar.setBackgroundHover(new java.awt.Color(204, 102, 0));
        btnEditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, -1, -1));

        jlbCorreoElectronico9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico9.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico9.setText("Documento de Identidad");
        jPanel1.add(jlbCorreoElectronico9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jlbCorreoElectronico10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico10.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico10.setText("Borrar");
        jPanel1.add(jlbCorreoElectronico10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, -1, -1));

        jlbCorreoElectronico11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico11.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico11.setText("Editar");
        jPanel1.add(jlbCorreoElectronico11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, -1, -1));

        Panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1010, 270));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void jtxtTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTokenActionPerformed

    private void btnSeleccionarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarImagenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador_RegistrarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador_RegistrarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador_RegistrarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador_RegistrarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador_RegistrarUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSPanelMaterial Panel;
    public RSMaterialComponent.RSButtonIconShadow btnAgregar;
    public RSMaterialComponent.RSButtonIconShadow btnBorrar;
    public RSMaterialComponent.RSButtonIconShadow btnEditar;
    public RSMaterialComponent.RSButtonMaterialOne btnSeleccionarImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public RSMaterialComponent.RSComboBoxMaterial jcbxTipoDoc;
    public RSMaterialComponent.RSComboBoxMaterial jcbxTipoEmpleado;
    public javax.swing.JLabel jlbCorreoElectronico;
    public javax.swing.JLabel jlbCorreoElectronico1;
    public javax.swing.JLabel jlbCorreoElectronico10;
    public javax.swing.JLabel jlbCorreoElectronico11;
    public javax.swing.JLabel jlbCorreoElectronico2;
    public javax.swing.JLabel jlbCorreoElectronico3;
    public javax.swing.JLabel jlbCorreoElectronico4;
    public javax.swing.JLabel jlbCorreoElectronico5;
    public javax.swing.JLabel jlbCorreoElectronico6;
    public javax.swing.JLabel jlbCorreoElectronico7;
    public javax.swing.JLabel jlbCorreoElectronico8;
    public javax.swing.JLabel jlbCorreoElectronico9;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtApellidos;
    public RSMaterialComponent.RSPasswordIconTwo jtxtContraseña;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtCorreo;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtNombres;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtNumDocumento;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtTelefono;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtToken;
    public RSMaterialComponent.RSTableMetro tblEmpleados;
    // End of variables declaration//GEN-END:variables

}
