/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package VistaAdministrador;

/**
 *
 * @author SARA
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /** Creates new form InterfazAdministrador */
    public MenuAdministrador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jPanel1 = new javax.swing.JPanel();
        PrincipalMenu = new RSMaterialComponent.RSPanelMaterial();
        rSPanelMaterial3 = new RSMaterialComponent.RSPanelMaterial();
        rSPanelBorderImage1 = new RSMaterialComponent.RSPanelBorderImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnCerrarSesion = new RSMaterialComponent.RSButtonMaterialOne();
        jbtnAdminEmpleados = new RSMaterialComponent.RSButtonMaterialOne();
        jbtnVentas = new RSMaterialComponent.RSButtonMaterialOne();
        jbtnInventario = new RSMaterialComponent.RSButtonMaterialOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrincipalMenu.setBackground(new java.awt.Color(238, 238, 238));
        PrincipalMenu.setPixels(0);

        javax.swing.GroupLayout PrincipalMenuLayout = new javax.swing.GroupLayout(PrincipalMenu);
        PrincipalMenu.setLayout(PrincipalMenuLayout);
        PrincipalMenuLayout.setHorizontalGroup(
            PrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        PrincipalMenuLayout.setVerticalGroup(
            PrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        jPanel1.add(PrincipalMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1070, 780));

        rSPanelMaterial1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 1070, 780));

        rSPanelMaterial3.setBackground(new java.awt.Color(204, 204, 204));
        rSPanelMaterial3.setPixels(0);
        rSPanelMaterial3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelBorderImage1.setBackground(new java.awt.Color(102, 102, 102));
        rSPanelBorderImage1.setForeground(new java.awt.Color(102, 102, 102));
        rSPanelBorderImage1.setBgBorder(new java.awt.Color(102, 102, 102));
        rSPanelBorderImage1.setRound(100);

        javax.swing.GroupLayout rSPanelBorderImage1Layout = new javax.swing.GroupLayout(rSPanelBorderImage1);
        rSPanelBorderImage1.setLayout(rSPanelBorderImage1Layout);
        rSPanelBorderImage1Layout.setHorizontalGroup(
            rSPanelBorderImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        rSPanelBorderImage1Layout.setVerticalGroup(
            rSPanelBorderImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        rSPanelMaterial3.add(rSPanelBorderImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO ADRESS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSPanelMaterial3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 310, -1));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMINISTADOR NAME");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSPanelMaterial3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 310, -1));

        jbtnCerrarSesion.setBackground(new java.awt.Color(102, 102, 102));
        jbtnCerrarSesion.setText("CERRAR SESIÓN");
        jbtnCerrarSesion.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnCerrarSesion.setRound(40);
        rSPanelMaterial3.add(jbtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 270, -1));

        jbtnAdminEmpleados.setBackground(new java.awt.Color(102, 102, 102));
        jbtnAdminEmpleados.setText("ADMINISTRAR EMPLEADOS");
        jbtnAdminEmpleados.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnAdminEmpleados.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnAdminEmpleados.setRound(40);
        rSPanelMaterial3.add(jbtnAdminEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 270, -1));

        jbtnVentas.setBackground(new java.awt.Color(102, 102, 102));
        jbtnVentas.setText("VENTAS");
        jbtnVentas.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnVentas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnVentas.setRound(40);
        rSPanelMaterial3.add(jbtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 270, -1));

        jbtnInventario.setBackground(new java.awt.Color(102, 102, 102));
        jbtnInventario.setText("INVENTARIO");
        jbtnInventario.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnInventario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnInventario.setRound(40);
        rSPanelMaterial3.add(jbtnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 270, -1));

        rSPanelMaterial1.add(rSPanelMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 780));

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSPanelMaterial PrincipalMenu;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public RSMaterialComponent.RSButtonMaterialOne jbtnAdminEmpleados;
    public RSMaterialComponent.RSButtonMaterialOne jbtnCerrarSesion;
    public RSMaterialComponent.RSButtonMaterialOne jbtnInventario;
    public RSMaterialComponent.RSButtonMaterialOne jbtnVentas;
    public RSMaterialComponent.RSPanelBorderImage rSPanelBorderImage1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial3;
    // End of variables declaration//GEN-END:variables

}
