/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package VistaVentas;

import VistaInventario.*;
import VistaAdministrador.*;

/**
 *
 * @author SARA
 */
public class Ventas_Registro2 extends javax.swing.JFrame {

    /** Creates new form InterfazAdministrador */
    public Ventas_Registro2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new RSMaterialComponent.RSPanelMaterial();
        btnExportarCatalogo = new RSMaterialComponent.RSButtonMaterialOne();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbRegistroDVentas = new RSMaterialComponent.RSTableMetro();
        jtxtImporteTotal = new RSMaterialComponent.RSTextFieldMaterial();
        jtxtPagaCon = new RSMaterialComponent.RSTextFieldMaterial();
        jtxtCambio = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnExportarCatalogo1 = new RSMaterialComponent.RSButtonMaterialOne();
        jbtnBoleta = new RSMaterialComponent.RSButtonMaterialOne();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscarPorNombreProducto = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxtBuscarPorID = new RSMaterialComponent.RSTextFieldIconTwo();
        jbtnAgregarProductosVentas = new RSMaterialComponent.RSButtonIconShadow();
        jbtnBuscarProductos = new RSMaterialComponent.RSButtonIconShadow();
        jlbCorreoElectronico10 = new javax.swing.JLabel();
        jlbCorreoElectronico12 = new javax.swing.JLabel();
        jlbCorreoElectronico7 = new javax.swing.JLabel();
        jlbCorreoElectronico2 = new javax.swing.JLabel();
        jbtnBorrarProductoTabla = new RSMaterialComponent.RSButtonIconShadow();
        jcbxFiltrarCat = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableMostraProductos = new RSMaterialComponent.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();
        jlbCorreoElectronico8 = new javax.swing.JLabel();
        jlblMostrarProductoVenta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtableMostraProductos1 = new RSMaterialComponent.RSTableMetro();
        jLabel7 = new javax.swing.JLabel();
        jbtnPagaCon = new RSMaterialComponent.RSButtonIconShadow();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setBgShade(new java.awt.Color(255, 255, 255));
        Panel.setIntensity(5);
        Panel.setPixels(0);
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExportarCatalogo.setBackground(new java.awt.Color(102, 102, 102));
        btnExportarCatalogo.setText("Factura");
        btnExportarCatalogo.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnExportarCatalogo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnExportarCatalogo.setRound(30);
        btnExportarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarCatalogoActionPerformed(evt);
            }
        });
        Panel.add(btnExportarCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 120, 30));

        jtbRegistroDVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Informacion", "Precio", "cantidad", "Promocion"
            }
        ));
        jtbRegistroDVentas.setBackgoundHead(new java.awt.Color(51, 51, 51));
        jtbRegistroDVentas.setBackgoundHover(new java.awt.Color(102, 102, 102));
        jtbRegistroDVentas.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        jtbRegistroDVentas.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        jtbRegistroDVentas.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jtbRegistroDVentas);

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1010, 140));

        jtxtImporteTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtImporteTotal.setText("00.00 S/.");
        jtxtImporteTotal.setColorMaterial(new java.awt.Color(102, 102, 102));
        jtxtImporteTotal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtImporteTotal.setPlaceholder("00.00");
        jtxtImporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtImporteTotalActionPerformed(evt);
            }
        });
        Panel.add(jtxtImporteTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 140, -1));

        jtxtPagaCon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtPagaCon.setText("00.00 S/.");
        jtxtPagaCon.setColorMaterial(new java.awt.Color(102, 102, 102));
        jtxtPagaCon.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtPagaCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPagaConActionPerformed(evt);
            }
        });
        Panel.add(jtxtPagaCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 140, -1));

        jtxtCambio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCambio.setText("00.00 S/.");
        jtxtCambio.setColorMaterial(new java.awt.Color(102, 102, 102));
        jtxtCambio.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Panel.add(jtxtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CAMBIO");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 170, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PAGÓ CON");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 170, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("TOTAL");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 100, 40));

        btnExportarCatalogo1.setBackground(new java.awt.Color(102, 102, 102));
        btnExportarCatalogo1.setText("Cancelar Venta");
        btnExportarCatalogo1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        btnExportarCatalogo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnExportarCatalogo1.setRound(30);
        btnExportarCatalogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarCatalogo1ActionPerformed(evt);
            }
        });
        Panel.add(btnExportarCatalogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 130, 30));

        jbtnBoleta.setBackground(new java.awt.Color(102, 102, 102));
        jbtnBoleta.setText("Boleta");
        jbtnBoleta.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnBoleta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnBoleta.setRound(30);
        jbtnBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBoletaActionPerformed(evt);
            }
        });
        Panel.add(jbtnBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, 120, 30));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tabla promociones");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 710, -1));

        jtxtBuscarPorNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        jtxtBuscarPorNombreProducto.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtBuscarPorNombreProducto.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtBuscarPorNombreProducto.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtBuscarPorNombreProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxtBuscarPorNombreProducto.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtBuscarPorNombreProducto.setPlaceholder("Nombre de producto");
        jtxtBuscarPorNombreProducto.setSelectionColor(new java.awt.Color(255, 153, 0));
        Panel.add(jtxtBuscarPorNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 180, 30));

        jtxtBuscarPorID.setForeground(new java.awt.Color(102, 102, 102));
        jtxtBuscarPorID.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtBuscarPorID.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtBuscarPorID.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtBuscarPorID.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT);
        jtxtBuscarPorID.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtBuscarPorID.setPlaceholder("ID");
        jtxtBuscarPorID.setSelectionColor(new java.awt.Color(255, 153, 0));
        Panel.add(jtxtBuscarPorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 110, 30));

        jbtnAgregarProductosVentas.setBackground(new java.awt.Color(0, 204, 102));
        jbtnAgregarProductosVentas.setBackgroundHover(new java.awt.Color(0, 102, 0));
        jbtnAgregarProductosVentas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        jbtnAgregarProductosVentas.setName("jbtnActualizarGDG"); // NOI18N
        Panel.add(jbtnAgregarProductosVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jbtnBuscarProductos.setBackground(new java.awt.Color(255, 204, 0));
        jbtnBuscarProductos.setBackgroundHover(new java.awt.Color(204, 102, 0));
        jbtnBuscarProductos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        jbtnBuscarProductos.setName("jbtnActualizarGDG"); // NOI18N
        Panel.add(jbtnBuscarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        jlbCorreoElectronico10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico10.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico10.setText("ID del Producto");
        Panel.add(jlbCorreoElectronico10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jlbCorreoElectronico12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico12.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico12.setText("Nombre del Producto");
        Panel.add(jlbCorreoElectronico12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        jlbCorreoElectronico7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico7.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico7.setText("Eliminar Producto de la tabla");
        Panel.add(jlbCorreoElectronico7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        jlbCorreoElectronico2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico2.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico2.setText("Buscar");
        Panel.add(jlbCorreoElectronico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        jbtnBorrarProductoTabla.setBackground(new java.awt.Color(255, 51, 51));
        jbtnBorrarProductoTabla.setBackgroundHover(new java.awt.Color(153, 0, 0));
        jbtnBorrarProductoTabla.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        jbtnBorrarProductoTabla.setName("jbtnActualizarGDG"); // NOI18N
        Panel.add(jbtnBorrarProductoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jcbxFiltrarCat.setForeground(new java.awt.Color(51, 51, 51));
        jcbxFiltrarCat.setColorMaterial(new java.awt.Color(255, 153, 0));
        Panel.add(jcbxFiltrarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 220, 40));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Productos");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        JtableMostraProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Stock", "Informacion", "Precio", "Imagen", "Categoria"
            }
        ));
        JtableMostraProductos.setBackgoundHead(new java.awt.Color(51, 51, 51));
        JtableMostraProductos.setBackgoundHover(new java.awt.Color(102, 102, 102));
        JtableMostraProductos.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        JtableMostraProductos.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        JtableMostraProductos.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(JtableMostraProductos);

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 710, 140));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Registro de Ventas");
        Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jlbCorreoElectronico8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico8.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico8.setText("Agregar");
        Panel.add(jlbCorreoElectronico8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, -1, -1));

        jlblMostrarProductoVenta.setBackground(new java.awt.Color(102, 153, 255));
        jlblMostrarProductoVenta.setForeground(new java.awt.Color(153, 255, 51));
        jlblMostrarProductoVenta.setToolTipText("");
        jlblMostrarProductoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel.add(jlblMostrarProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 180, 170));

        JtableMostraProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre Promoción", "Descuento/Beneficio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtableMostraProductos1.setBackgoundHead(new java.awt.Color(102, 102, 102));
        JtableMostraProductos1.setBackgoundHover(new java.awt.Color(102, 102, 102));
        JtableMostraProductos1.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        JtableMostraProductos1.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        JtableMostraProductos1.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane3.setViewportView(JtableMostraProductos1);

        Panel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 710, 120));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Filtrar por Categorias:");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jbtnPagaCon.setBackground(new java.awt.Color(153, 153, 153));
        jbtnPagaCon.setBackgroundHover(new java.awt.Color(102, 102, 102));
        jbtnPagaCon.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ATTACH_MONEY);
        jbtnPagaCon.setInheritsPopupMenu(true);
        Panel.add(jbtnPagaCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarCatalogoActionPerformed

    private void jtxtImporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtImporteTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtImporteTotalActionPerformed

    private void jtxtPagaConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPagaConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPagaConActionPerformed

    private void btnExportarCatalogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCatalogo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarCatalogo1ActionPerformed

    private void jbtnBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBoletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas_Registro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas_Registro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas_Registro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas_Registro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas_Registro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSTableMetro JtableMostraProductos;
    public RSMaterialComponent.RSTableMetro JtableMostraProductos1;
    public RSMaterialComponent.RSPanelMaterial Panel;
    public RSMaterialComponent.RSButtonMaterialOne btnExportarCatalogo;
    public RSMaterialComponent.RSButtonMaterialOne btnExportarCatalogo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public RSMaterialComponent.RSButtonIconShadow jbtnAgregarProductosVentas;
    public RSMaterialComponent.RSButtonMaterialOne jbtnBoleta;
    public RSMaterialComponent.RSButtonIconShadow jbtnBorrarProductoTabla;
    public RSMaterialComponent.RSButtonIconShadow jbtnBuscarProductos;
    public RSMaterialComponent.RSButtonIconShadow jbtnPagaCon;
    public RSMaterialComponent.RSComboBoxMaterial jcbxFiltrarCat;
    private javax.swing.JLabel jlbCorreoElectronico10;
    private javax.swing.JLabel jlbCorreoElectronico12;
    private javax.swing.JLabel jlbCorreoElectronico2;
    private javax.swing.JLabel jlbCorreoElectronico7;
    private javax.swing.JLabel jlbCorreoElectronico8;
    public javax.swing.JLabel jlblMostrarProductoVenta;
    public RSMaterialComponent.RSTableMetro jtbRegistroDVentas;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtBuscarPorID;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtBuscarPorNombreProducto;
    public RSMaterialComponent.RSTextFieldMaterial jtxtCambio;
    public RSMaterialComponent.RSTextFieldMaterial jtxtImporteTotal;
    public RSMaterialComponent.RSTextFieldMaterial jtxtPagaCon;
    // End of variables declaration//GEN-END:variables

}
