/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package VistaVentas;

import VistaInventario.*;
import VistaAdministrador.*;

/**
 *
 * @author SARA
 */
public class Ventas_Promociones extends javax.swing.JFrame {

    /** Creates new form InterfazAdministrador */
    public Ventas_Promociones() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMoveWindow1 = new rojeru_san.complementos.RSMoveWindow();
        rSMaterialMove1 = new rojeru_san.complementos.RSMaterialMove();
        Panel = new RSMaterialComponent.RSPanelMaterial();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblMostrarPromociones = new RSMaterialComponent.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbxFiltrarCat = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtxfNombreProducto = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico = new javax.swing.JLabel();
        jtxtNombrePromo = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico1 = new javax.swing.JLabel();
        jtxtPrecioVenta = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico6 = new javax.swing.JLabel();
        jlbCorreoElectronico8 = new javax.swing.JLabel();
        btnAgregar = new RSMaterialComponent.RSButtonIconShadow();
        btnBorrar = new RSMaterialComponent.RSButtonIconShadow();
        btnEditar = new RSMaterialComponent.RSButtonIconShadow();
        jlbCorreoElectronico10 = new javax.swing.JLabel();
        jlbCorreoElectronico11 = new javax.swing.JLabel();
        jlbCorreoElectronico9 = new javax.swing.JLabel();
        jtxtCantPromo = new RSMaterialComponent.RSTextFieldIconTwo();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxfIDProducto = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico2 = new javax.swing.JLabel();
        btnLimpiarCampos = new RSMaterialComponent.RSButtonIconShadow();
        jlbLimpiarCampos1 = new javax.swing.JLabel();
        jlbLimpiarCampos2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableMostraProductos = new RSMaterialComponent.RSTableMetro();
        btnBuscar = new RSMaterialComponent.RSButtonIconShadow();
        jlbCorreoElectronico12 = new javax.swing.JLabel();
        jtxtBuscarPorID = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico13 = new javax.swing.JLabel();
        jtxtBuscarPorNombrePromo = new RSMaterialComponent.RSTextFieldIconTwo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setBgShade(new java.awt.Color(255, 255, 255));
        Panel.setIntensity(5);
        Panel.setPixels(0);
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblMostrarPromociones.setBackground(new java.awt.Color(255, 255, 255));
        jtblMostrarPromociones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Promo", "Producto", "Tipo", "Condición", "Beneficio"
            }
        ));
        jtblMostrarPromociones.setBackgoundHead(new java.awt.Color(51, 51, 51));
        jtblMostrarPromociones.setBackgoundHover(new java.awt.Color(102, 102, 102));
        jtblMostrarPromociones.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        jtblMostrarPromociones.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        jtblMostrarPromociones.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jtblMostrarPromociones);

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 710, 180));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Promociones");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Filtrar por Categorias:");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jcbxFiltrarCat.setForeground(new java.awt.Color(51, 51, 51));
        jcbxFiltrarCat.setColorMaterial(new java.awt.Color(255, 153, 0));
        Panel.add(jcbxFiltrarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 230, 40));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Productos");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfNombreProducto.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto.setPlaceholder("Nombre de producto");
        jtxfNombreProducto.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxfNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 30));

        jlbCorreoElectronico.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico.setText("Nombre del producto");
        jPanel1.add(jlbCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jtxtNombrePromo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNombrePromo.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtNombrePromo.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtNombrePromo.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtNombrePromo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT);
        jtxtNombrePromo.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtNombrePromo.setPlaceholder("Nombre de la promoción");
        jtxtNombrePromo.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtNombrePromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, 30));

        jlbCorreoElectronico1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico1.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico1.setText("Nombre de la promoción");
        jPanel1.add(jlbCorreoElectronico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jtxtPrecioVenta.setForeground(new java.awt.Color(102, 102, 102));
        jtxtPrecioVenta.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtPrecioVenta.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtPrecioVenta.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtPrecioVenta.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);
        jtxtPrecioVenta.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtPrecioVenta.setPlaceholder(" S/.");
        jtxtPrecioVenta.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 240, 30));

        jlbCorreoElectronico6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico6.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico6.setText("Agregar");
        jPanel1.add(jlbCorreoElectronico6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jlbCorreoElectronico8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico8.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico8.setText("Precio Final");
        jPanel1.add(jlbCorreoElectronico8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 204, 102));
        btnAgregar.setBackgroundHover(new java.awt.Color(0, 102, 0));
        btnAgregar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnAgregar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        btnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        btnBorrar.setBackgroundHover(new java.awt.Color(153, 0, 0));
        btnBorrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnBorrar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 204, 0));
        btnEditar.setBackgroundHover(new java.awt.Color(204, 102, 0));
        btnEditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jlbCorreoElectronico10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico10.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico10.setText("Borrar");
        jPanel1.add(jlbCorreoElectronico10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        jlbCorreoElectronico11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico11.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico11.setText("Editar");
        jPanel1.add(jlbCorreoElectronico11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        jlbCorreoElectronico9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico9.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico9.setText("Cantidad de la promoción");
        jPanel1.add(jlbCorreoElectronico9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jtxtCantPromo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtCantPromo.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtCantPromo.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtCantPromo.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtCantPromo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.COMMENT);
        jtxtCantPromo.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtCantPromo.setPlaceholder("Cantidad");
        jtxtCantPromo.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtCantPromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 30));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("promociones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, -1));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registro de ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, -1));

        jtxfIDProducto.setForeground(new java.awt.Color(102, 102, 102));
        jtxfIDProducto.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfIDProducto.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfIDProducto.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfIDProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfIDProducto.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfIDProducto.setPlaceholder("ID de producto");
        jtxfIDProducto.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxfIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 240, 30));

        jlbCorreoElectronico2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico2.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico2.setText("ID del producto");
        jPanel1.add(jlbCorreoElectronico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnLimpiarCampos.setBackground(new java.awt.Color(51, 153, 255));
        btnLimpiarCampos.setBackgroundHover(new java.awt.Color(0, 102, 255));
        btnLimpiarCampos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR_ALL);
        btnLimpiarCampos.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jlbLimpiarCampos1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbLimpiarCampos1.setForeground(new java.awt.Color(51, 51, 51));
        jlbLimpiarCampos1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbLimpiarCampos1.setText("Limpiar");
        jPanel1.add(jlbLimpiarCampos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        jlbLimpiarCampos2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbLimpiarCampos2.setForeground(new java.awt.Color(51, 51, 51));
        jlbLimpiarCampos2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbLimpiarCampos2.setText("campos");
        jPanel1.add(jlbLimpiarCampos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        Panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 620));

        JtableMostraProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Stock", "Informacion", "Precio", "Categoria"
            }
        ));
        JtableMostraProductos.setBackgoundHead(new java.awt.Color(51, 51, 51));
        JtableMostraProductos.setBackgoundHover(new java.awt.Color(102, 102, 102));
        JtableMostraProductos.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        JtableMostraProductos.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        JtableMostraProductos.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(JtableMostraProductos);

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 710, 140));

        btnBuscar.setBackground(new java.awt.Color(255, 204, 0));
        btnBuscar.setBackgroundHover(new java.awt.Color(204, 102, 0));
        btnBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnBuscar.setName("jbtnActualizarGDG"); // NOI18N
        Panel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        jlbCorreoElectronico12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico12.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico12.setText("ID Promo");
        Panel.add(jlbCorreoElectronico12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jtxtBuscarPorID.setForeground(new java.awt.Color(102, 102, 102));
        jtxtBuscarPorID.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtBuscarPorID.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtBuscarPorID.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtBuscarPorID.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT);
        jtxtBuscarPorID.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtBuscarPorID.setPlaceholder("ID");
        jtxtBuscarPorID.setSelectionColor(new java.awt.Color(255, 153, 0));
        Panel.add(jtxtBuscarPorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 110, 30));

        jlbCorreoElectronico13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico13.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCorreoElectronico13.setText("Nombre del Promo");
        Panel.add(jlbCorreoElectronico13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jtxtBuscarPorNombrePromo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtBuscarPorNombrePromo.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtBuscarPorNombrePromo.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtBuscarPorNombrePromo.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtBuscarPorNombrePromo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxtBuscarPorNombrePromo.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtBuscarPorNombrePromo.setPlaceholder("Nombre de la promoción");
        jtxtBuscarPorNombrePromo.setSelectionColor(new java.awt.Color(255, 153, 0));
        Panel.add(jtxtBuscarPorNombrePromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 210, 30));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas_Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas_Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas_Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas_Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas_Promociones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSTableMetro JtableMostraProductos;
    public RSMaterialComponent.RSPanelMaterial Panel;
    public RSMaterialComponent.RSButtonIconShadow btnAgregar;
    public RSMaterialComponent.RSButtonIconShadow btnBorrar;
    public RSMaterialComponent.RSButtonIconShadow btnBuscar;
    public RSMaterialComponent.RSButtonIconShadow btnEditar;
    public RSMaterialComponent.RSButtonIconShadow btnLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public RSMaterialComponent.RSComboBoxMaterial jcbxFiltrarCat;
    private javax.swing.JLabel jlbCorreoElectronico;
    private javax.swing.JLabel jlbCorreoElectronico1;
    private javax.swing.JLabel jlbCorreoElectronico10;
    private javax.swing.JLabel jlbCorreoElectronico11;
    private javax.swing.JLabel jlbCorreoElectronico12;
    private javax.swing.JLabel jlbCorreoElectronico13;
    private javax.swing.JLabel jlbCorreoElectronico2;
    private javax.swing.JLabel jlbCorreoElectronico6;
    private javax.swing.JLabel jlbCorreoElectronico8;
    private javax.swing.JLabel jlbCorreoElectronico9;
    public javax.swing.JLabel jlbLimpiarCampos1;
    public javax.swing.JLabel jlbLimpiarCampos2;
    public RSMaterialComponent.RSTableMetro jtblMostrarPromociones;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfIDProducto;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtBuscarPorID;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtBuscarPorNombrePromo;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtCantPromo;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtNombrePromo;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtPrecioVenta;
    private rojeru_san.complementos.RSMaterialMove rSMaterialMove1;
    private rojeru_san.complementos.RSMoveWindow rSMoveWindow1;
    // End of variables declaration//GEN-END:variables

}
