/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package VistaRegistrarPersonasExternas;

import VistaAdministrador.*;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author SARA
 */
public class clientes extends javax.swing.JFrame {

    /** Creates new form InterfazAdministrador */
    public clientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new RSMaterialComponent.RSPanelMaterial();
        jPanel1 = new javax.swing.JPanel();
        jlbNombres = new javax.swing.JLabel();
        jtxtNombres = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbApellidos = new javax.swing.JLabel();
        jtxtApellidos = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico8 = new javax.swing.JLabel();
        jtxtCorreo = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbTelefono = new javax.swing.JLabel();
        jtxtTelefono = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbTipoEmpleado = new javax.swing.JLabel();
        jcbxTipoEmpleado = new RSMaterialComponent.RSComboBoxMaterial();
        jlbDocumento = new javax.swing.JLabel();
        jtxtNumDocumento = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbAgregar = new javax.swing.JLabel();
        btnAgregar = new RSMaterialComponent.RSButtonIconShadow();
        jlbEditar = new javax.swing.JLabel();
        btnEditar = new RSMaterialComponent.RSButtonIconShadow();
        jlbBorrar2 = new javax.swing.JLabel();
        btnBorrar = new RSMaterialComponent.RSButtonIconShadow();
        jlbLimpiarCampos1 = new javax.swing.JLabel();
        jlbLimpiarCampos2 = new javax.swing.JLabel();
        btnLimpiarCampos = new RSMaterialComponent.RSButtonIconShadow();
        jtxtApellidos1 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbDocumento1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleados1 = new RSMaterialComponent.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxfNombreProducto = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico = new javax.swing.JLabel();
        jlbCorreoElectronico2 = new javax.swing.JLabel();
        jlbCorreoElectronico3 = new javax.swing.JLabel();
        jtxfNombreProducto1 = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxfNombreProducto2 = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxfNombreProducto3 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico4 = new javax.swing.JLabel();
        jlbCorreoElectronico5 = new javax.swing.JLabel();
        jtxfNombreProducto4 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico6 = new javax.swing.JLabel();
        jtxfNombreProducto5 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtxfNombreProducto12 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico16 = new javax.swing.JLabel();
        jlbCorreoElectronico17 = new javax.swing.JLabel();
        jlbCorreoElectronico18 = new javax.swing.JLabel();
        jtxfNombreProducto13 = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxfNombreProducto14 = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxfNombreProducto15 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico19 = new javax.swing.JLabel();
        jlbCorreoElectronico20 = new javax.swing.JLabel();
        jtxfNombreProducto16 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico21 = new javax.swing.JLabel();
        jtxfNombreProducto17 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jtxfNombreProducto18 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico23 = new javax.swing.JLabel();
        jlbCorreoElectronico24 = new javax.swing.JLabel();
        jlbCorreoElectronico25 = new javax.swing.JLabel();
        jtxfNombreProducto19 = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxfNombreProducto20 = new RSMaterialComponent.RSTextFieldIconTwo();
        jtxfNombreProducto21 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico26 = new javax.swing.JLabel();
        jlbCorreoElectronico27 = new javax.swing.JLabel();
        jtxfNombreProducto22 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico28 = new javax.swing.JLabel();
        jtxfNombreProducto23 = new RSMaterialComponent.RSTextFieldIconTwo();
        jlbCorreoElectronico29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setBgShade(new java.awt.Color(255, 255, 255));
        Panel.setIntensity(5);
        Panel.setPixels(0);
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbNombres.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbNombres.setForeground(new java.awt.Color(51, 51, 51));
        jlbNombres.setText("Nombres");
        jPanel1.add(jlbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtNombres.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNombres.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtNombres.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtNombres.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtNombres.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        jtxtNombres.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtNombres.setPlaceholder("Nombres");
        jtxtNombres.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 30));

        jlbApellidos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbApellidos.setForeground(new java.awt.Color(51, 51, 51));
        jlbApellidos.setText("Apellidos");
        jPanel1.add(jlbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jtxtApellidos.setForeground(new java.awt.Color(102, 102, 102));
        jtxtApellidos.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtApellidos.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtApellidos.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtApellidos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        jtxtApellidos.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtApellidos.setPlaceholder("Apellidos");
        jtxtApellidos.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 150, 30));

        jlbCorreoElectronico8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico8.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico8.setText("Correo electrónico");
        jPanel1.add(jlbCorreoElectronico8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jtxtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtCorreo.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtCorreo.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtCorreo.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtCorreo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EMAIL);
        jtxtCorreo.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtCorreo.setPlaceholder(" abc@mail.com");
        jtxtCorreo.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, 30));

        jlbTelefono.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jlbTelefono.setText("Telf. de Contacto");
        jPanel1.add(jlbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jtxtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        jtxtTelefono.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtTelefono.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtTelefono.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtTelefono.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE);
        jtxtTelefono.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtTelefono.setPlaceholder("999999999");
        jtxtTelefono.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, 30));

        jlbTipoEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbTipoEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        jlbTipoEmpleado.setText("Genero");
        jPanel1.add(jlbTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jcbxTipoEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        jcbxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Femenino", "Masculino" }));
        jcbxTipoEmpleado.setColorMaterial(new java.awt.Color(255, 153, 0));
        jPanel1.add(jcbxTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 150, 30));

        jlbDocumento.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbDocumento.setForeground(new java.awt.Color(51, 51, 51));
        jlbDocumento.setText("Edad");
        jPanel1.add(jlbDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jtxtNumDocumento.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNumDocumento.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtNumDocumento.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtNumDocumento.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtNumDocumento.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT);
        jtxtNumDocumento.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtNumDocumento.setPlaceholder("55555555");
        jtxtNumDocumento.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtNumDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 150, 30));

        jlbAgregar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbAgregar.setForeground(new java.awt.Color(51, 51, 51));
        jlbAgregar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbAgregar.setText("Agregar");
        jPanel1.add(jlbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 204, 102));
        btnAgregar.setBackgroundHover(new java.awt.Color(0, 102, 0));
        btnAgregar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE_OUTLINE);
        btnAgregar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jlbEditar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbEditar.setForeground(new java.awt.Color(51, 51, 51));
        jlbEditar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbEditar.setText("Actualizar");
        jPanel1.add(jlbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 204, 0));
        btnEditar.setBackgroundHover(new java.awt.Color(204, 102, 0));
        btnEditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jlbBorrar2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbBorrar2.setForeground(new java.awt.Color(51, 51, 51));
        jlbBorrar2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbBorrar2.setText("Borrar");
        jPanel1.add(jlbBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        btnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        btnBorrar.setBackgroundHover(new java.awt.Color(153, 0, 0));
        btnBorrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnBorrar.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        jlbLimpiarCampos1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbLimpiarCampos1.setForeground(new java.awt.Color(51, 51, 51));
        jlbLimpiarCampos1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbLimpiarCampos1.setText("Limpiar");
        jPanel1.add(jlbLimpiarCampos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        jlbLimpiarCampos2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbLimpiarCampos2.setForeground(new java.awt.Color(51, 51, 51));
        jlbLimpiarCampos2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbLimpiarCampos2.setText("campos");
        jPanel1.add(jlbLimpiarCampos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        btnLimpiarCampos.setBackground(new java.awt.Color(51, 153, 255));
        btnLimpiarCampos.setBackgroundHover(new java.awt.Color(0, 102, 255));
        btnLimpiarCampos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR_ALL);
        btnLimpiarCampos.setName("jbtnActualizarGDG"); // NOI18N
        jPanel1.add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jtxtApellidos1.setForeground(new java.awt.Color(102, 102, 102));
        jtxtApellidos1.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtApellidos1.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtApellidos1.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtApellidos1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        jtxtApellidos1.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtApellidos1.setPlaceholder("Apellidos");
        jtxtApellidos1.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel1.add(jtxtApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, 30));

        jlbDocumento1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbDocumento1.setForeground(new java.awt.Color(51, 51, 51));
        jlbDocumento1.setText("Doc. Identidad");
        jPanel1.add(jlbDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Registro de Clientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 180));

        tblEmpleados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Doc.Identidad", "Nombres", "Apellidos", "Edad", "Genero", "Tlf.", "Correo"
            }
        ));
        tblEmpleados1.setBackgoundHead(new java.awt.Color(51, 51, 51));
        tblEmpleados1.setBackgoundHover(new java.awt.Color(102, 102, 102));
        tblEmpleados1.setColorPrimaryText(new java.awt.Color(51, 51, 51));
        tblEmpleados1.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        tblEmpleados1.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(tblEmpleados1);

        Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1000, 180));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Preferencias");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto.setBorderColor(new java.awt.Color(255, 51, 0));
        jtxfNombreProducto.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto.setPlaceholder("Categoría 3");
        jtxfNombreProducto.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(jtxfNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 30));

        jlbCorreoElectronico.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico.setText("3er puesto");
        jPanel2.add(jlbCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jlbCorreoElectronico2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico2.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico2.setText("1er puesto");
        jPanel2.add(jlbCorreoElectronico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jlbCorreoElectronico3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico3.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico3.setText("2do puesto");
        jPanel2.add(jlbCorreoElectronico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jtxfNombreProducto1.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto1.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfNombreProducto1.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto1.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto1.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto1.setPlaceholder("Categoría 1");
        jtxfNombreProducto1.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(jtxfNombreProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 30));

        jtxfNombreProducto2.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto2.setBorderColor(new java.awt.Color(255, 102, 0));
        jtxfNombreProducto2.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto2.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto2.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto2.setPlaceholder("Categoría 2");
        jtxfNombreProducto2.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(jtxfNombreProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 30));

        jtxfNombreProducto3.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto3.setBorderColor(new java.awt.Color(255, 102, 0));
        jtxfNombreProducto3.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto3.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto3.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto3.setPlaceholder("Cant.");
        jtxfNombreProducto3.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(jtxfNombreProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 70, 30));

        jlbCorreoElectronico4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico4.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico4.setText("Cantidad");
        jPanel2.add(jlbCorreoElectronico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jlbCorreoElectronico5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico5.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico5.setText("Cantidad");
        jPanel2.add(jlbCorreoElectronico5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jtxfNombreProducto4.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto4.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfNombreProducto4.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto4.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto4.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto4.setPlaceholder("Cant.");
        jtxfNombreProducto4.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(jtxfNombreProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 70, 30));

        jlbCorreoElectronico6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico6.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico6.setText("Cantidad");
        jPanel2.add(jlbCorreoElectronico6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jtxfNombreProducto5.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto5.setBorderColor(new java.awt.Color(255, 51, 0));
        jtxfNombreProducto5.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto5.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto5.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto5.setPlaceholder("Cant.");
        jtxfNombreProducto5.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(jtxfNombreProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 70, 30));

        jlbCorreoElectronico7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico7.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCorreoElectronico7.setText("3 categorias de productos más compradas");
        jPanel2.add(jlbCorreoElectronico7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        Panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 290, 220));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfNombreProducto12.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto12.setBorderColor(new java.awt.Color(255, 51, 0));
        jtxfNombreProducto12.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto12.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto12.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto12.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto12.setPlaceholder("Producto 3");
        jtxfNombreProducto12.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel4.add(jtxfNombreProducto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 30));

        jlbCorreoElectronico16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico16.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico16.setText("3er puesto");
        jPanel4.add(jlbCorreoElectronico16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jlbCorreoElectronico17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico17.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico17.setText("1er puesto");
        jPanel4.add(jlbCorreoElectronico17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jlbCorreoElectronico18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico18.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico18.setText("2do puesto");
        jPanel4.add(jlbCorreoElectronico18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jtxfNombreProducto13.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto13.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfNombreProducto13.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto13.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto13.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto13.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto13.setPlaceholder("Producto 1");
        jtxfNombreProducto13.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel4.add(jtxfNombreProducto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 30));

        jtxfNombreProducto14.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto14.setBorderColor(new java.awt.Color(255, 102, 0));
        jtxfNombreProducto14.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto14.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto14.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto14.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto14.setPlaceholder("Producto 2");
        jtxfNombreProducto14.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel4.add(jtxfNombreProducto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 30));

        jtxfNombreProducto15.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto15.setBorderColor(new java.awt.Color(255, 102, 0));
        jtxfNombreProducto15.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto15.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto15.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto15.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto15.setPlaceholder("Cant.");
        jtxfNombreProducto15.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel4.add(jtxfNombreProducto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 70, 30));

        jlbCorreoElectronico19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico19.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico19.setText("Cantidad");
        jPanel4.add(jlbCorreoElectronico19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jlbCorreoElectronico20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico20.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico20.setText("Cantidad");
        jPanel4.add(jlbCorreoElectronico20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jtxfNombreProducto16.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto16.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfNombreProducto16.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto16.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto16.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto16.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto16.setPlaceholder("Cant.");
        jtxfNombreProducto16.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel4.add(jtxfNombreProducto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 70, 30));

        jlbCorreoElectronico21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico21.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico21.setText("Cantidad");
        jPanel4.add(jlbCorreoElectronico21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jtxfNombreProducto17.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto17.setBorderColor(new java.awt.Color(255, 51, 0));
        jtxfNombreProducto17.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto17.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto17.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto17.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto17.setPlaceholder("Cant.");
        jtxfNombreProducto17.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel4.add(jtxfNombreProducto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 70, 30));

        jlbCorreoElectronico22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico22.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCorreoElectronico22.setText("3 productos más compradas");
        jPanel4.add(jlbCorreoElectronico22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        Panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 290, 220));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfNombreProducto18.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto18.setBorderColor(new java.awt.Color(255, 51, 0));
        jtxfNombreProducto18.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto18.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto18.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto18.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto18.setPlaceholder("Nombre de producto");
        jtxfNombreProducto18.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel5.add(jtxfNombreProducto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 30));

        jlbCorreoElectronico23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico23.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico23.setText("3er puesto");
        jPanel5.add(jlbCorreoElectronico23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jlbCorreoElectronico24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico24.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico24.setText("1er puesto");
        jPanel5.add(jlbCorreoElectronico24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jlbCorreoElectronico25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico25.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico25.setText("2do puesto");
        jPanel5.add(jlbCorreoElectronico25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jtxfNombreProducto19.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto19.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfNombreProducto19.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto19.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto19.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto19.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto19.setPlaceholder("Nombre de producto");
        jtxfNombreProducto19.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel5.add(jtxfNombreProducto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 30));

        jtxfNombreProducto20.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto20.setBorderColor(new java.awt.Color(255, 102, 0));
        jtxfNombreProducto20.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto20.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto20.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto20.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto20.setPlaceholder("Nombre de producto");
        jtxfNombreProducto20.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel5.add(jtxfNombreProducto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 30));

        jtxfNombreProducto21.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto21.setBorderColor(new java.awt.Color(255, 102, 0));
        jtxfNombreProducto21.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto21.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto21.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto21.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto21.setPlaceholder("Cant.");
        jtxfNombreProducto21.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel5.add(jtxfNombreProducto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 70, 30));

        jlbCorreoElectronico26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico26.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico26.setText("Cantidad");
        jPanel5.add(jlbCorreoElectronico26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jlbCorreoElectronico27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico27.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico27.setText("Cantidad");
        jPanel5.add(jlbCorreoElectronico27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jtxfNombreProducto22.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto22.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxfNombreProducto22.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto22.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto22.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto22.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto22.setPlaceholder("Cant.");
        jtxfNombreProducto22.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel5.add(jtxfNombreProducto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 70, 30));

        jlbCorreoElectronico28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico28.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico28.setText("Cantidad");
        jPanel5.add(jlbCorreoElectronico28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jtxfNombreProducto23.setForeground(new java.awt.Color(102, 102, 102));
        jtxfNombreProducto23.setBorderColor(new java.awt.Color(255, 51, 0));
        jtxfNombreProducto23.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxfNombreProducto23.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxfNombreProducto23.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BATTERY_STD);
        jtxfNombreProducto23.setPhColor(new java.awt.Color(153, 153, 153));
        jtxfNombreProducto23.setPlaceholder("Cant.");
        jtxfNombreProducto23.setSelectionColor(new java.awt.Color(255, 153, 0));
        jPanel5.add(jtxfNombreProducto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 70, 30));

        jlbCorreoElectronico29.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jlbCorreoElectronico29.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCorreoElectronico29.setText("Categorias menos compradas");
        jPanel5.add(jlbCorreoElectronico29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        Panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 290, 220));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSPanelMaterial Panel;
    public RSMaterialComponent.RSButtonIconShadow btnAgregar;
    public RSMaterialComponent.RSButtonIconShadow btnBorrar;
    public RSMaterialComponent.RSButtonIconShadow btnEditar;
    public RSMaterialComponent.RSButtonIconShadow btnLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public RSMaterialComponent.RSComboBoxMaterial jcbxTipoEmpleado;
    public javax.swing.JLabel jlbAgregar;
    public javax.swing.JLabel jlbApellidos;
    public javax.swing.JLabel jlbBorrar2;
    private javax.swing.JLabel jlbCorreoElectronico;
    private javax.swing.JLabel jlbCorreoElectronico16;
    private javax.swing.JLabel jlbCorreoElectronico17;
    private javax.swing.JLabel jlbCorreoElectronico18;
    private javax.swing.JLabel jlbCorreoElectronico19;
    private javax.swing.JLabel jlbCorreoElectronico2;
    private javax.swing.JLabel jlbCorreoElectronico20;
    private javax.swing.JLabel jlbCorreoElectronico21;
    private javax.swing.JLabel jlbCorreoElectronico22;
    private javax.swing.JLabel jlbCorreoElectronico23;
    private javax.swing.JLabel jlbCorreoElectronico24;
    private javax.swing.JLabel jlbCorreoElectronico25;
    private javax.swing.JLabel jlbCorreoElectronico26;
    private javax.swing.JLabel jlbCorreoElectronico27;
    private javax.swing.JLabel jlbCorreoElectronico28;
    private javax.swing.JLabel jlbCorreoElectronico29;
    private javax.swing.JLabel jlbCorreoElectronico3;
    private javax.swing.JLabel jlbCorreoElectronico4;
    private javax.swing.JLabel jlbCorreoElectronico5;
    private javax.swing.JLabel jlbCorreoElectronico6;
    private javax.swing.JLabel jlbCorreoElectronico7;
    public javax.swing.JLabel jlbCorreoElectronico8;
    public javax.swing.JLabel jlbDocumento;
    public javax.swing.JLabel jlbDocumento1;
    public javax.swing.JLabel jlbEditar;
    public javax.swing.JLabel jlbLimpiarCampos1;
    public javax.swing.JLabel jlbLimpiarCampos2;
    public javax.swing.JLabel jlbNombres;
    public javax.swing.JLabel jlbTelefono;
    public javax.swing.JLabel jlbTipoEmpleado;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto1;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto12;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto13;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto14;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto15;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto16;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto17;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto18;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto19;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto2;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto20;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto21;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto22;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto23;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto3;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto4;
    public RSMaterialComponent.RSTextFieldIconTwo jtxfNombreProducto5;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtApellidos;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtApellidos1;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtCorreo;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtNombres;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtNumDocumento;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtTelefono;
    public RSMaterialComponent.RSTableMetro tblEmpleados1;
    // End of variables declaration//GEN-END:variables

}
