/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaLogin;

/**
 *
 * @author jheremyPonte
 */
public class Recuperar_1Correo extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public Recuperar_1Correo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jLabel2 = new javax.swing.JLabel();
        jtxtfIngresaCorreo = new RSMaterialComponent.RSTextFieldIconTwo();
        jbtnEnviarCodigo = new RSMaterialComponent.RSButtonMaterialOne();
        jbtnVolverAtras = new RSMaterialComponent.RSButtonMaterialOne();
        jlbCorreoElectronico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setBgShade(new java.awt.Color(102, 102, 102));
        rSPanelMaterial1.setIntensity(0);
        rSPanelMaterial1.setRound(25);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RECUPERAR CONTRASEÑA");
        rSPanelMaterial1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 390, -1));

        jtxtfIngresaCorreo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtfIngresaCorreo.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtfIngresaCorreo.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtfIngresaCorreo.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtfIngresaCorreo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EMAIL);
        jtxtfIngresaCorreo.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtfIngresaCorreo.setPlaceholder(" abc@mail.com");
        jtxtfIngresaCorreo.setSelectionColor(new java.awt.Color(255, 153, 0));
        rSPanelMaterial1.add(jtxtfIngresaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, -1));

        jbtnEnviarCodigo.setBackground(new java.awt.Color(102, 102, 102));
        jbtnEnviarCodigo.setText("Enviar código");
        jbtnEnviarCodigo.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnEnviarCodigo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnEnviarCodigo.setRound(40);
        jbtnEnviarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnviarCodigoActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(jbtnEnviarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 120, -1));

        jbtnVolverAtras.setBackground(new java.awt.Color(102, 102, 102));
        jbtnVolverAtras.setText("Volver");
        jbtnVolverAtras.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnVolverAtras.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnVolverAtras.setRound(40);
        jbtnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverAtrasActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(jbtnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, -1));

        jlbCorreoElectronico.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jlbCorreoElectronico.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreoElectronico.setText("INGRESAR CORREO ELECTRÓNICO");
        rSPanelMaterial1.add(jlbCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEnviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnviarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEnviarCodigoActionPerformed

    private void jbtnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnVolverAtrasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public RSMaterialComponent.RSButtonMaterialOne jbtnEnviarCodigo;
    public RSMaterialComponent.RSButtonMaterialOne jbtnVolverAtras;
    public javax.swing.JLabel jlbCorreoElectronico;
    public RSMaterialComponent.RSTextFieldIconTwo jtxtfIngresaCorreo;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    // End of variables declaration//GEN-END:variables
}
