/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaLogin;

/**
 *
 * @author jheremyPonte
 */
public class Recuperar extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public Recuperar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrincipalRecuperar = new RSMaterialComponent.RSPanelMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrincipalRecuperar.setBackground(new java.awt.Color(255, 255, 255));
        PrincipalRecuperar.setBgShade(new java.awt.Color(102, 102, 102));
        PrincipalRecuperar.setIntensity(0);
        PrincipalRecuperar.setRound(25);
        PrincipalRecuperar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PrincipalRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSPanelMaterial PrincipalRecuperar;
    // End of variables declaration//GEN-END:variables
}
