/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaLogin;

/**
 *
 * @author jheremyPonte
 */
public class Recuperar_3Contraseña extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public Recuperar_3Contraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jLabel2 = new javax.swing.JLabel();
        jbtnCancelar = new RSMaterialComponent.RSButtonMaterialOne();
        jbtnReestablecer = new RSMaterialComponent.RSButtonMaterialOne();
        JLBContraseña = new javax.swing.JLabel();
        jtxtfContraseña = new RSMaterialComponent.RSPasswordIconTwo();
        jtxtfContraseña1 = new RSMaterialComponent.RSPasswordIconTwo();
        JLBContraseña1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial1.setBgShade(new java.awt.Color(102, 102, 102));
        rSPanelMaterial1.setIntensity(0);
        rSPanelMaterial1.setRound(25);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RECUPARAR CONTRASEÑA");
        rSPanelMaterial1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 390, -1));

        jbtnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnCancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnCancelar.setRound(30);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 90, 30));

        jbtnReestablecer.setBackground(new java.awt.Color(102, 102, 102));
        jbtnReestablecer.setText("Reestablecer");
        jbtnReestablecer.setBackgroundHover(new java.awt.Color(153, 153, 153));
        jbtnReestablecer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jbtnReestablecer.setRound(40);
        jbtnReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReestablecerActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(jbtnReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 120, -1));

        JLBContraseña.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        JLBContraseña.setForeground(new java.awt.Color(51, 51, 51));
        JLBContraseña.setText("NUEVA CONTRASEÑA");
        rSPanelMaterial1.add(JLBContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jtxtfContraseña.setForeground(new java.awt.Color(102, 102, 102));
        jtxtfContraseña.setToolTipText("");
        jtxtfContraseña.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtfContraseña.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtfContraseña.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtfContraseña.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtfContraseña.setPlaceholder("* * * * * * * ");
        jtxtfContraseña.setSelectionColor(new java.awt.Color(255, 153, 0));
        rSPanelMaterial1.add(jtxtfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 300, -1));

        jtxtfContraseña1.setForeground(new java.awt.Color(102, 102, 102));
        jtxtfContraseña1.setToolTipText("");
        jtxtfContraseña1.setBorderColor(new java.awt.Color(255, 153, 0));
        jtxtfContraseña1.setCaretColor(new java.awt.Color(0, 153, 255));
        jtxtfContraseña1.setColorIcon(new java.awt.Color(204, 204, 204));
        jtxtfContraseña1.setPhColor(new java.awt.Color(153, 153, 153));
        jtxtfContraseña1.setPlaceholder("* * * * * * * ");
        jtxtfContraseña1.setSelectionColor(new java.awt.Color(255, 153, 0));
        rSPanelMaterial1.add(jtxtfContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, -1));

        JLBContraseña1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        JLBContraseña1.setForeground(new java.awt.Color(51, 51, 51));
        JLBContraseña1.setText("VALIDAR CONTRASEÑA");
        rSPanelMaterial1.add(JLBContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReestablecerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReestablecerActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLBContraseña;
    public javax.swing.JLabel JLBContraseña1;
    private javax.swing.JLabel jLabel2;
    public RSMaterialComponent.RSButtonMaterialOne jbtnCancelar;
    public RSMaterialComponent.RSButtonMaterialOne jbtnReestablecer;
    public RSMaterialComponent.RSPasswordIconTwo jtxtfContraseña;
    public RSMaterialComponent.RSPasswordIconTwo jtxtfContraseña1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    // End of variables declaration//GEN-END:variables
}
